# Generated by Django 5.2.4 on 2025-08-25 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_amount_order_final_amount_and_more'),
        ('products', '0002_remove_product_image_url_product_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders.coupon'),
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the flash sale event', max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(help_text='Start time of the flash sale')),
                ('end_date', models.DateTimeField(help_text='End time of the flash sale')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flash sale is active')),
                ('products', models.ManyToManyField(help_text='List of products included in the flash sale', related_name='flash_sales', to='products.product')),
            ],
            options={
                'db_table': 'flash_sales',
                'indexes': [models.Index(fields=['start_date'], name='idx_flash_sales_start_date'), models.Index(fields=['end_date'], name='idx_flash_sales_end_date'), models.Index(fields=['is_active'], name='idx_flash_sales_is_active')],
            },
        ),
    ]
